name: PBB_pertemuan_1
description: A new Flutter project.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  # intl: ^0.20.2
#   flutter:       # Required for every Flutter project
#     sdk: flutter # Required for every Flutter project
#   flutter_localizations: # Required to enable localization
#     sdk: flutter         # Required to enable localization

#   cupertino_icons: ^1.0.8 # Only required if you use Cupertino (iOS style) icons

# dev_dependencies:
#   flutter_test:
#     sdk: flutter # Required for a Flutter project that includes tests

#   flutter_lints: ^6.0.0 # Contains a set of recommended lints for Flutter code

# flutter:

#   uses-material-design: true # Required if you use the Material icon font

#   generate: true # Enables generation of localized strings from arb files

#   config: # App-specific configuration flags that mirror `flutter config`
#     enable-swift-package-manager: true

#   assets:  # Lists assets, such as image files
#     - images/a_dot_burr.png
#     - images/a_dot_ham.png

#   licenses: # Lists additional license files to be bundled with the app
#     - assets/my_license.txt

#   fonts:              # Required if your app uses custom fonts
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700