name: widget_preview_scaffold
description: Scaffolding for Flutter Widget Previews
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.9.0
dependencies:
  dtd: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.1
  hello_world:
    path: ../..
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
flutter:
  uses-material-design: true